# Generated by Django 5.1.6 on 2025-02-26 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='体重')),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='体脂肪率')),
                ('record_date', models.DateTimeField(verbose_name='日付')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '体重',
                'verbose_name_plural': '体重',
                'ordering': ['-created_at'],
            },
        ),
    ]
