# Generated by Django 5.1.6 on 2025-03-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightrecord',
            name='fat',
            field=models.FloatField(blank=True, null=True, verbose_name='体脂肪率'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='weight',
            field=models.FloatField(verbose_name='体重'),
        ),
    ]
