# Generated by Django 5.1.6 on 2025-08-02 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0002_alter_weightrecord_fat_alter_weightrecord_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='作成日時（自動設定）'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='fat',
            field=models.FloatField(blank=True, help_text='体脂肪率（%）、オプション', null=True, verbose_name='体脂肪率'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='record_date',
            field=models.DateTimeField(help_text='記録日時', verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='更新日時（自動更新）'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='user',
            field=models.ForeignKey(help_text='記録を所有するユーザー', on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='weight',
            field=models.FloatField(help_text='体重（kg）', verbose_name='体重'),
        ),
    ]
