# Generated by Django 5.1.6 on 2025-03-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='public/recipes/{recipe.pk}/steps'),
        ),
    ]
