# Generated by Django 5.1.6 on 2025-03-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipestep_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='public/recipes'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='public/recipes/steps'),
        ),
    ]
