# Generated by Django 5.1.6 on 2025-03-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_image_alter_recipestep_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('簡単', '簡単'), ('中級', '中級'), ('上級', '上級')], default='簡単', max_length=16, verbose_name='難易度'),
        ),
    ]
