# Generated by Django 5.1.6 on 2025-03-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_recipetag_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetag',
            name='name',
            field=models.CharField(max_length=64, verbose_name='タグ名'),
        ),
    ]
