# Generated by Django 5.1.6 on 2025-03-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipetag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='biotin',
            field=models.FloatField(blank=True, null=True, verbose_name='ビオチン（μg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='calcium',
            field=models.FloatField(blank=True, null=True, verbose_name='カルシウム（mg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cholesterol',
            field=models.FloatField(blank=True, null=True, verbose_name='コレステロール（mg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='chromium',
            field=models.FloatField(blank=True, null=True, verbose_name='クロム（μg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='copper',
            field=models.FloatField(blank=True, null=True, verbose_name='銅（mg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dietary_fiber',
            field=models.FloatField(blank=True, null=True, verbose_name='食物繊維（g）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='folic_acid',
            field=models.FloatField(blank=True, null=True, verbose_name='葉酸（μg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='iodine',
            field=models.FloatField(blank=True, null=True, verbose_name='ヨウ素（μg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='iron',
            field=models.FloatField(blank=True, null=True, verbose_name='鉄（mg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='magnesium',
            field=models.FloatField(blank=True, null=True, verbose_name='マグネシウム（mg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='manganese',
            field=models.FloatField(blank=True, null=True, verbose_name='マンガン（mg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='molybdenum',
            field=models.FloatField(blank=True, null=True, verbose_name='モリブデン（μg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='niacin',
            field=models.FloatField(blank=True, null=True, verbose_name='ナイアシン（mgNE）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pantothenic_acid',
            field=models.FloatField(blank=True, null=True, verbose_name='パントテン酸（mg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='phosphorus',
            field=models.FloatField(blank=True, null=True, verbose_name='リン（mg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='potassium',
            field=models.FloatField(blank=True, null=True, verbose_name='カリウム（mg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='salt_equivalent',
            field=models.FloatField(blank=True, null=True, verbose_name='食塩相当量（g）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='selenium',
            field=models.FloatField(blank=True, null=True, verbose_name='セレン（μg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sodium',
            field=models.FloatField(blank=True, null=True, verbose_name='ナトリウム（g）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vitamin_a',
            field=models.FloatField(blank=True, null=True, verbose_name='ビタミンA（μgRAE）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vitamin_b1',
            field=models.FloatField(blank=True, null=True, verbose_name='ビタミンB1（mg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vitamin_b12',
            field=models.FloatField(blank=True, null=True, verbose_name='ビタミンB12（μg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vitamin_b2',
            field=models.FloatField(blank=True, null=True, verbose_name='ビタミンB2（mg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vitamin_b6',
            field=models.FloatField(blank=True, null=True, verbose_name='ビタミンB6（mg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vitamin_c',
            field=models.FloatField(blank=True, null=True, verbose_name='ビタミンC（mg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vitamin_d',
            field=models.FloatField(blank=True, null=True, verbose_name='ビタミンD（μg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vitamin_e',
            field=models.FloatField(blank=True, null=True, verbose_name='ビタミンE（mg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vitamin_k',
            field=models.FloatField(blank=True, null=True, verbose_name='ビタミンK（μg）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='zinc',
            field=models.FloatField(blank=True, null=True, verbose_name='亜鉛（mg）'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_calories',
            field=models.FloatField(default=0, verbose_name='カロリー'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_carbs',
            field=models.FloatField(default=0, verbose_name='炭水化物'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_fat',
            field=models.FloatField(default=0, verbose_name='脂質'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_protein',
            field=models.FloatField(default=0, verbose_name='たんぱく質'),
        ),
    ]
