# Generated by Django 5.1.6 on 2025-03-18 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingapplication',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 17, 1, 16, 984723, tzinfo=datetime.timezone.utc)),
        ),
    ]
