# Generated by Django 5.1.6 on 2025-03-18 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_alter_trainingapplication_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingapplication',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 18, 30, 0, 948256, tzinfo=datetime.timezone.utc)),
        ),
    ]
