# Generated by Django 5.1.6 on 2025-03-18 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_alter_trainingapplication_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingapplication',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 18, 35, 6, 212660, tzinfo=datetime.timezone.utc)),
        ),
    ]
