# Generated by Django 5.1.6 on 2025-03-21 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0008_alter_trainingapplication_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingapplication',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
