# Generated by Django 5.1.6 on 2025-04-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0009_alter_trainingapplication_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='経歴'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='certifications',
            field=models.TextField(blank=True, verbose_name='資格等'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='経歴'),
        ),
    ]
