# Generated by Django 5.1.6 on 2025-04-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0010_trainerprofile_introduction_alter_trainerprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='trainingapplication',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='trainingapplication',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='trainingapplication',
            name='user',
        ),
        migrations.DeleteModel(
            name='TrainerProfile',
        ),
        migrations.DeleteModel(
            name='TrainingPlan',
        ),
        migrations.DeleteModel(
            name='TrainingApplication',
        ),
    ]
