# Generated by Django 5.1.6 on 2025-04-13 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0011_remove_trainingplan_trainer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='自己紹介')),
                ('specialties', models.JSONField(default=list, help_text="例: ['筋トレ', 'ピラティス']", verbose_name='得意分野（ジャンル）')),
                ('certifications', models.JSONField(default=list, help_text="例: ['NSCA-CPT', 'JATI-ATI']", verbose_name='保有資格')),
                ('career', models.TextField(blank=True, verbose_name='経歴・実績')),
                ('intro_video_url', models.URLField(blank=True, null=True, verbose_name='紹介動画URL')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開フラグ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
