# Generated by Django 5.1.6 on 2025-04-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0012_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公開フラグ'),
        ),
    ]
