# Generated by Django 5.1.6 on 2025-08-02 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='セット名')),
                ('description', models.TextField(blank=True, help_text='セットの説明', null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('user_id', models.ForeignKey(help_text='ユーザー', on_delete=django.db.models.deletion.CASCADE, related_name='mysets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MySetExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='種目名', max_length=255, verbose_name='種目名')),
                ('order', models.IntegerField(help_text='種目の順番', verbose_name='順番')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('myset_id', models.ForeignKey(help_text='マイセット', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='myset.myset')),
            ],
        ),
        migrations.CreateModel(
            name='MySetExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='セットの順番', verbose_name='順番')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='重量(kg)')),
                ('reps', models.IntegerField(blank=True, null=True, verbose_name='回数')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='距離')),
                ('distance_unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='距離単位')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='時間')),
                ('duration_unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='時間単位')),
                ('fat_burn', models.FloatField(blank=True, null=True, verbose_name='脂肪燃焼(kcal)')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('myset_exercise_id', models.ForeignKey(help_text='マイセット種目', on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='myset.mysetexercise')),
            ],
        ),
    ]
