# Generated by Django 5.1.6 on 2025-08-03 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
        ('myset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysetexercise',
            name='name',
        ),
        migrations.AddField(
            model_name='mysetexercise',
            name='exercise',
            field=models.ForeignKey(blank=True, help_text='エクササイズ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myset_exercises', to='exercise.exercise'),
        ),
    ]
