# Generated by Django 5.1.6 on 2025-08-02 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='種目名', max_length=255, verbose_name='種目名')),
                ('order', models.IntegerField(help_text='種目の順番', verbose_name='順番')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='セットの順番', verbose_name='順番')),
                ('weight', models.FloatField(blank=True, help_text='重量(kg)', null=True, verbose_name='重量(kg)')),
                ('reps', models.IntegerField(blank=True, help_text='回数', null=True, verbose_name='回数')),
                ('distance', models.FloatField(blank=True, help_text='距離', null=True, verbose_name='距離')),
                ('distance_unit', models.CharField(blank=True, help_text='距離単位', max_length=10, null=True, verbose_name='距離単位')),
                ('duration', models.IntegerField(blank=True, help_text='時間', null=True, verbose_name='時間')),
                ('duration_unit', models.CharField(blank=True, help_text='時間単位', max_length=10, null=True, verbose_name='時間単位')),
                ('fat_burn', models.FloatField(blank=True, help_text='脂肪燃焼(kcal)', null=True, verbose_name='脂肪燃焼(kcal)')),
                ('memo', models.TextField(blank=True, help_text='セットのメモ', null=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('workout_exercise_id', models.ForeignKey(help_text='トレーニング種目', on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercise_sets', to='workout.workoutexercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='セッション名（胸トレーニングなど）', max_length=255, verbose_name='セッション名')),
                ('date', models.DateField(help_text='トレーニング日', verbose_name='日付')),
                ('memo', models.TextField(blank=True, help_text='トレーニングのメモ', null=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('user_id', models.ForeignKey(help_text='ユーザー', on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='workout_session_id',
            field=models.ForeignKey(help_text='トレーニングセッション', on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workout.workoutsession'),
        ),
    ]
