# Generated by Django 5.1.6 on 2025-08-03 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='カテゴリ名（胸、背中、肩など）', max_length=50, unique=True, verbose_name='カテゴリ名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'エクササイズカテゴリ',
                'verbose_name_plural': 'エクササイズカテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='エクササイズ名', max_length=255, verbose_name='エクササイズ名')),
                ('description', models.TextField(help_text='エクササイズの説明', verbose_name='説明')),
                ('is_official', models.BooleanField(default=False, help_text='システム提供の公式エクササイズかどうか', verbose_name='公式エクササイズ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='ユーザーが作成した場合の作成者（公式の場合はNull）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('category', models.ForeignKey(help_text='エクササイズのカテゴリ', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercise.exercisecategory', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': 'エクササイズ',
                'verbose_name_plural': 'エクササイズ',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_official', False)), fields=('name', 'category', 'created_by'), name='unique_user_exercise_per_category')],
            },
        ),
    ]
