# Generated by Django 5.1.6 on 2025-03-02 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('carbs', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '食品',
                'verbose_name_plural': '食品',
            },
        ),
        migrations.CreateModel(
            name='MealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_of_day', models.CharField(choices=[('朝食', '朝食'), ('昼食', '昼食'), ('夕食', '夕食'), ('間食', '間食')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='meals/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '食事記録',
                'verbose_name_plural': '食事記録',
            },
        ),
        migrations.CreateModel(
            name='MealRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('meal_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.mealitem')),
                ('meal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='meal.mealrecord')),
            ],
            options={
                'verbose_name': '食事記録の詳細',
                'verbose_name_plural': '食事記録の詳細',
            },
        ),
    ]
