# Generated by Django 5.1.6 on 2025-05-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_mealitem_biotin_mealitem_calcium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='is_official',
            field=models.BooleanField(default=True, verbose_name='公式フラグ'),
        ),
    ]
