# Generated by Django 5.1.6 on 2025-06-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_mealitem_is_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='official_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='公式食品ID'),
        ),
    ]
