# Generated by Django 5.1.6 on 2025-06-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0008_mealitem_official_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='カンマ区切りの検索用キーワード', null=True),
        ),
    ]
