# Generated by Django 5.1.6 on 2025-07-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0009_mealitem_search_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='jan_ean_code',
            field=models.CharField(blank=True, help_text='商品のバーコード番号', max_length=20, null=True, verbose_name='JAN/EANコード'),
        ),
    ]
