# Generated by Django 5.1.6 on 2025-03-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_hub', '0003_recipepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipePage',
        ),
    ]
