# Generated by Django 5.1.6 on 2025-03-30 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_hub', '0005_articlecategory_articlepage_categories_articletag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletag',
            name='content_object',
        ),
        migrations.AddField(
            model_name='articletag',
            name='content_object',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='health_hub.articlepage'),
            preserve_default=False,
        ),
    ]
