# Generated by Django 5.1.6 on 2025-03-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_hub', '0006_remove_articletag_content_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
