# Generated by Django 5.1.6 on 2025-03-30 15:28

import django.db.models.deletion
import modelcluster.contrib.taggit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_hub', '0007_remove_articlepage_tags_delete_articletag'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='health_hub.articlepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='health_hub.ArticleTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
