# Generated by Django 5.1.6 on 2025-03-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_hub', '0008_articletag_articlepage_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
