# Generated by Django 5.1.6 on 2025-03-30 15:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_hub', '0009_remove_articlepage_tags_delete_articletag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.RichTextField(help_text='記事の本文を入力してください'),
        ),
    ]
