# Generated by Django 5.1.6 on 2025-04-12 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_hub', '0011_customimage_customrendition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='health_hub.customimage'),
        ),
    ]
