# Generated by Django 5.1.6 on 2025-04-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_hub', '0013_articlecategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
