# Generated by Django 5.1.6 on 2025-07-20 03:56

import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_hub', '0014_alter_articlecategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
    ]
