# Generated by Django 5.1.6 on 2025-02-27 12:33

import django.db.models.deletion
import training.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('weight', '重量'), ('distance', '距離')], max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('memo', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='training.trainingsession')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True, validators=[training.models.validate_positive])),
                ('reps', models.IntegerField(blank=True, null=True, validators=[training.models.validate_positive])),
                ('distance', models.FloatField(blank=True, null=True, validators=[training.models.validate_positive])),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training.workout')),
            ],
        ),
    ]
