# Generated by Django 5.1.6 on 2025-04-26 10:54

import django.db.models.deletion
import training.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='このマイセットを作成したユーザー（トレーナーまたは本人）', on_delete=django.db.models.deletion.CASCADE, related_name='created_my_sets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='このマイセットを使うユーザー', on_delete=django.db.models.deletion.CASCADE, related_name='my_sets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MySetSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('myset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training.myset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_set_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MySetWorkoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('weight', '重量'), ('distance', '距離')], max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('memo', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='training.mysetsession')),
            ],
        ),
        migrations.CreateModel(
            name='MySetWorkoutSetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True, validators=[training.models.validate_positive])),
                ('reps', models.IntegerField(blank=True, null=True, validators=[training.models.validate_positive])),
                ('distance', models.FloatField(blank=True, null=True, validators=[training.models.validate_positive])),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training.mysetworkoutrecord')),
            ],
        ),
        migrations.CreateModel(
            name='MyWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('weight', '重量'), ('distance', '距離')], max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('memo', models.TextField(blank=True, null=True)),
                ('myset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='training.myset')),
            ],
        ),
        migrations.CreateModel(
            name='MyWorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True, validators=[training.models.validate_positive])),
                ('reps', models.IntegerField(blank=True, null=True, validators=[training.models.validate_positive])),
                ('distance', models.FloatField(blank=True, null=True, validators=[training.models.validate_positive])),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training.myworkout')),
            ],
        ),
    ]
