# Generated by Django 5.1.6 on 2025-05-19 11:23

import training.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_myset_mysetsession_mysetworkoutrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysetworkoutsetrecord',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[training.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='myworkoutset',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[training.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='distance',
            field=models.FloatField(blank=True, null=True, validators=[training.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[training.models.validate_non_negative]),
        ),
    ]
